### ISSUE TITLE
添加跳过环境监测的选项

### ISSUE THREAD

**Issue by UVJkiNTQ** [infstellar/python-git-program-launcher-cpp#1]
本地有安装git但没有检测出来，程序执行报错无法安装。

建议添加一个跳过环境监测的选项，让确认有运行环境的用户跳过检测。

[pgpl_cpp.log](https://github.com/user-attachments/files/16323750/pgpl_cpp.log)

**Comment by infstellar** [comment]
感谢反馈，现在还不能调用系统的git，以后会添加，然后日志里还有一些其他的bug会修复
